---
title: 'Data Analytics: Support Vector Machine In- Class '
author: "Brendan Donnelly"
date: "September 10, 2020"
output:
  pdf_document: default
  html_document: default
---

```{r}
library(ggplot2)
library(e1071)

data("iris")
head(iris)
str(iris)

qplot(Petal.Length, Petal.Width, data=iris, color = Species)
```

SVM Model 1: Set-up, Classification Plot, and Table

```{r sv}
svm_model1 <- svm(Species~., data = iris)
summary(svm_model1)

plot(svm_model1, data = iris, 
     Petal.Width~Petal.Length, slice = list(Sepal.Width =3, Sepal.Length =4))


pred1<- predict(svm_model1, iris)

table1 <- table(Predicted = pred1, Actua = iris$Species)
table1
```

# Misclassification Rate: Model 1
```{r rate}
Model1_accuracyRate = sum(diag(table1))/sum(table1)
Model1_accuracyRate

Model1_MissClassificationRate = 1 - Model1_accuracyRate
Model1_MissClassificationRate
```

# SVM Model 2- Kernel = "linear"
```{r svm2}
svm_model2 <- svm(Species~., data = iris, kernel = "linear")
summary(svm_model2)

plot(svm_model2, data = iris, 
     Petal.Width~Petal.Length, slice = list(Sepal.Width =3, Sepal.Length =4))

pred2<- predict(svm_model2, iris)

table2 <- table(Predicted = pred2, Actua = iris$Species)
table2
```



```{r rate2}
Model2_accuracyRate = sum(diag(table2))/sum(table2)
Model2_accuracyRate

Model2_MissClassificationRate = 1 - Model2_accuracyRate
Model2_MissClassificationRate
```



# SVM Model 3- Kernel = "polynmial"
```{r svm3}
svm_model3 <- svm(Species~., data = iris, kernel = "polynomial")
summary(svm_model3)

plot(svm_model3, data = iris, 
     Petal.Width~Petal.Length, slice = list(Sepal.Width =3, Sepal.Length =4))

pred3<- predict(svm_model3, iris)

table3 <- table(Predicted = pred3, Actua = iris$Species)
table3
```


```{r rate2}
Model3_accuracyRate = sum(diag(table3))/sum(table3)
Model3_accuracyRate

Model3_MissClassificationRate = 1 - Model3_accuracyRate
Model3_MissClassificationRate
```
